import git from "./git.svg";
const content = [
  {
    id: 1,
    name: "Expense Tracker",
    body: "Expense tracker used to monitor finances, uses context api for state management, Nodejs(Express) for backend and Mongodb as sql database. Design inspiration by me  ",
    tools: [
      "React",
      "Stlyed Components",
      "GSAP",
      "NodeJs",
      "Context Api",
      "Express",
      "MongoDb",
    ],
    url: "https://expense-history-tracker.netlify.app/",
    git: git,
    gitUrl: "https://github.com/thatFemicode/Mini-Expense-Tracker-MERN-",
  },
  {
    id: 2,
    name: "Baradel Designo",
    body: "A fictional travel website, design inspiration was gotten from Frontend mentor as a challenge",
    tools: ["HTML", "SASS", "JS"],
    url: "https://baradeldesigno.netlify.app/",
    git: git,
    gitUrl: "https://github.com/thatFemicode/Baradel-Designo-Project",
  },
  {
    id: 3,
    name: "Golden State Warriors ",
    body: "A Landing page dedicated to the Golden state warriors paying respect to past accomplishment and looking at the future",
    tools: ["React", "Stlyed Components", "GSAP"],
    url: "https://goldenstate.netlify.app/",
    git: git,
    gitUrl: "https://github.com/thatFemicode/Gallery-GSW",
  },
  {
    id: 4,
    name: "NBA BLOG APP",
    body: "Blog website built to connect nba lovers together and discuss about their favorite players, uses Redux for state management, Nodejs(Express) for backend and Mongodb as sql database. Design inspiration by me",
    tools: [
      "React",
      "Stlyed Components",
      "GSAP",
      "NodeJs",
      "Redux",
      "Express",
      "MongoDb",
    ],
    url: "https://nbaapp.netlify.app/",
    git: git,
    gitUrl: "https://github.com/thatFemicode/NBA-BLOG-WEBSITE",
  },
  {
    id: 5,
    name: "BMI Calculator",
    body: "A bmi calculator used to calculate body mass index for individuals, uses the metric system for its measurement and local storage to persists data ",
    tools: ["React", "Stlyed Components", "GSAP"],
    url: "https://expressbmicalculator.netlify.app/",
    git: git,
    gitUrl: "https://github.com/thatFemicode/BMI-calculator",
  },
  {
    id: 6,
    name: "Black Women Rule",
    body: "A website i built to appreciate black women during black history month and women's month ",
    tools: ["React", "Stlyed Components", "GSAP"],
    url: "https://blackwomen.netlify.app/",
    git: git,
    gitUrl: "https://github.com/thatFemicode/Black-Women",
  },
  {
    id: 7,
    name: "ExpressSea NFT Marketplace",
    body: "A mini NFT market place built to mimic OpenSea, built this project after learning a bit about web3.0 and nft's as a beginner project. Web app has a landing page and a market place.  ",
    tools: ["React", "Stlyed Components", "GSAP", "framer-motion"],
    url: "https://expresssea.netlify.app/",
    git: git,
    gitUrl: "https://github.com/thatFemicode/NFT-marketplace",
  },
];

export default content;
